//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigiTutorService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Apoyo
    {
        public string id_estudianteApoyado { get; set; }
        public string id_estudianteDaApoyo { get; set; }
        public int id_tecnologia { get; set; }
        public System.DateTime fecha { get; set; }
    
        public virtual Estudiante Estudiante { get; set; }
        public virtual Estudiante Estudiante1 { get; set; }
        public virtual Tecnologia Tecnologia { get; set; }
    }
}
