//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigiTutorService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contenido
    {
        public int id_publicacion { get; set; }
        public string enlace_video { get; set; }
        public string enlace_extra { get; set; }
        public Nullable<int> id_documento { get; set; }
    
        public virtual Documento Documento { get; set; }
        public virtual Publicacion Publicacion { get; set; }
    }
}
