//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigiTutorService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tutoria
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tutoria()
        {
            this.Estudiantes = new HashSet<Estudiante>();
        }
    
        public int id_publicacion { get; set; }
        public int id { get; set; }
        public System.DateTime fecha_tutoria { get; set; }
        public string lugar { get; set; }
        public string costo { get; set; }
    
        public virtual Publicacion Publicacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Estudiante> Estudiantes { get; set; }
    }
}
