//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigiTutorService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public string id { get; set; }
        public string contrasena { get; set; }
        public System.DateTime fecha_creacion { get; set; }
        public string nombre { get; set; }
        public string apellido { get; set; }
        public string correo_principal { get; set; }
        public bool activo { get; set; }
        public bool is_admin { get; set; }
    
        public virtual Estudiante Estudiante { get; set; }
    }
}
