//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigiTutorService.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Estudiante_sigue_EstudianteDAO
    {
        public int id { get; set; }
        public string id_estudianteSeguido { get; set; }
        public string id_estudianteSeguidor { get; set; }
    
        public virtual EstudianteDAO Estudiante { get; set; }
        public virtual EstudianteDAO Estudiante1 { get; set; }
    }
}
