//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigiTutorService.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class EstudianteDAO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EstudianteDAO()
        {
            this.Apoyoes = new HashSet<ApoyoDAO>();
            this.Comentarios = new HashSet<ComentarioDAO>();
            this.Apoyoes1 = new HashSet<ApoyoDAO>();
            this.Evaluacions = new HashSet<EvaluacionDAO>();
            this.Publicacions = new HashSet<PublicacionDAO>();
            this.Estudiante1 = new HashSet<EstudianteDAO>();
            this.Estudiantes = new HashSet<EstudianteDAO>();
            this.Tutorias = new HashSet<TutoriaDAO>();
            this.Tecnologias = new HashSet<TecnologiaDAO>();
        }
    
        public string id_usuario { get; set; }
        public int id_pais { get; set; }
        public int id_universidad { get; set; }
        public string telefono_celular { get; set; }
        public string telefono_fijo { get; set; }
        public string correo_secundario { get; set; }
        public string foto { get; set; }
        public string descripcion { get; set; }
        public int reputacion { get; set; }
        public int participacion { get; set; }
        public int apoyos_disponibles { get; set; }
        public int numero_seguidores { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ApoyoDAO> Apoyoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ComentarioDAO> Comentarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ApoyoDAO> Apoyoes1 { get; set; }
        public virtual PaisDAO Pai { get; set; }
        public virtual UniversidadDAO Universidad { get; set; }
        public virtual UsuarioDAO Usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EvaluacionDAO> Evaluacions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PublicacionDAO> Publicacions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EstudianteDAO> Estudiante1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EstudianteDAO> Estudiantes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TutoriaDAO> Tutorias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TecnologiaDAO> Tecnologias { get; set; }
    }
}
